### ISSUE TITLE
Backend Deployment Guide is 404

### ISSUE THREAD

**Issue by markjbrown** [microsoft/TailwindTraders#16]
This guide is missing in the repo, https://github.com/microsoft/TailwindTraders/blob/master/Documents/DeploymentGuide.md Not sure if it was moved.

**Comment by ivilches** [comment]
Hello. Many things have been changed since August, not just documents' paths :) ; I'm affraid that doc is out of date. All you can get a look to https://github.com/Microsoft/TailwindTraders-Backend#deployment-scenarios) for Backend's different deployment scenarios, and to https://github.com/Microsoft/TailwindTraders-Website for Frontend web app.

**Comment by olgamarti** [comment]
Please, if you are still having doubts about the documentation, reopen the issue. We will be very happy to help!
