### ISSUE TITLE
Demo script: Managing backend with Azure Kubernetes Service (AKS), can't find the files to donwload to storage account

### ISSUE THREAD

**Issue by buzzfrog** [microsoft/TailwindTraders#5]
I get an error when trying to follow these links:
product-list.zip: https://1drv.ms/u/s!Asa-selZwiFlg_QVhlC9O8sRaYcAvQ
coupon-list.zip: https://1drv.ms/u/s!Asa-selZwiFlg_QT-bBrsoBLq2yrSQ
product-detail.zip: https://1drv.ms/u/s!Asa-selZwiFlg_QUACkViDBOqpII_Q
profiles-list.zip: https://1drv.ms/u/s!Asa-selZwiFlg_QSAl40JUEPiKivDw

**Comment by dasanagu** [comment]
Sorry for the confusion, this step is not longer required because we changed the gvalues files to use our public storage account, so now the links are populated in that file with the following URLs:
https://tailwindtraders.blob.core.windows.net/product-list
https://tailwindtraders.blob.core.windows.net/product-detail
https://tailwindtraders.blob.core.windows.net/coupon-list
https://tailwindtraders.blob.core.windows.net/profiles-list
We have deleted that step from the demo script.
